import {useState} from 'react';
import type {AdminState} from '@shared/astana';
import {useAstana,useRefreshAstana,useRosterSelection} from '@/hooks/useAstana';
import {LoadState,Notice} from './AstanaLayout';
import {Dialog,DialogContent,DialogHeader,DialogTitle,DialogDescription} from '@/components/ui/dialog';
import type {WheelDisputeIdentity} from '@/lib/wheel-dispute';
import './astana.css';
export default function AstanaDisputeDialog({teamNames,identity,onClose,onComplete,onStale}:{teamNames:string[];identity:WheelDisputeIdentity;onClose:()=>void;onComplete:()=>void;onStale:()=>void}){
 const admin=useAstana<AdminState>('/admin');const refresh=useRefreshAstana();const [selected,setSelected]=useRosterSelection<Record<string,string>>(admin.data?.rosterRevision??-1,{}),[busy,setBusy]=useState(false),[error,setError]=useState('');
 const names=Array.from(new Set(teamNames.filter(Boolean))).slice(0,3);
 async function swap(){setBusy(true);setError('');try{const response=await fetch('/api/admin/dashboard/wheel-dispute/rotate',{method:'POST',credentials:'same-origin',headers:{'Content-Type':'application/json'},body:JSON.stringify({...identity,guestIds:names.map(n=>selected[n]),rosterRevision:admin.data!.rosterRevision})});const result=await response.json().catch(()=>null);if(!response.ok){if(response.status===409){onStale();await refresh();}throw new Error(result?.message??`Could not resolve dispute (${response.status}).`);}await refresh();onComplete();onClose();}catch(e){setError((e as Error).message);}finally{setBusy(false);}}
 return <Dialog open onOpenChange={open=>{if(!open&&!busy)onClose();}}><DialogContent className="max-w-3xl"><div className="astana p-0"><DialogHeader><DialogTitle>Founders’ dispute</DialogTitle><DialogDescription>Select one member from each affected team. They rotate to the next team shown.</DialogDescription></DialogHeader>{admin.isLoading||admin.error?<LoadState error={admin.error}/>:names.length<2?<p className="my-6">Only one team was selected. A swap needs at least two teams; keep building.</p>:<div className="astana-form my-6">{names.map((name,i)=><label key={name}>{name} → {names[(i+1)%names.length]}<select value={selected[name]??''} onChange={e=>setSelected(s=>({...s,[name]:e.target.value}))}><option value="">Choose a builder</option>{admin.data?.teams.find(t=>t.name===name)?.members.map(g=><option key={g.id} value={g.id}>{g.name}</option>)}</select></label>)}</div>}<Notice error message={error}/><div className="astana-actions"><button className="btn btn-primary" disabled={busy||names.length<2||!names.every(n=>selected[n])||!admin.data} onClick={swap}>{busy?'Saving…':'Confirm swap / rotation'}</button><button className="btn" disabled={busy} onClick={onClose}>Close</button></div></div></DialogContent></Dialog>;
}
