import {useEffect,useState} from 'react';
import type {AdminState} from '@shared/astana';
import {astanaRequest,useRefreshAstana} from '@/hooks/useAstana';
import {Notice} from './AstanaLayout';
export default function JudgingPanel({state}:{state:AdminState}){
 const [ids,setIds]=useState<string[]>(()=>[0,1,2].map(i=>state.draftProjectIds[i]??'')),[revision,setRevision]=useState(state.judgingRevision),[dirty,setDirty]=useState(false),[busy,setBusy]=useState(false),[error,setError]=useState(''),[message,setMessage]=useState(''),[confirmReveal,setConfirmReveal]=useState(false);const refresh=useRefreshAstana();
 useEffect(()=>{if(!dirty){setIds([0,1,2].map(i=>state.draftProjectIds[i]??''));setRevision(state.judgingRevision);}},[state,dirty]);
 async function save(){setBusy(true);setError('');try{await astanaRequest('/admin/winners','PUT',{projectIds:ids,judgingRevision:revision});await refresh();setDirty(false);setMessage('Private draft saved. Publish when you are ready for the reveal.');}catch(e){setError((e as Error).message);}finally{setBusy(false);}}
 async function publish(){setBusy(true);setError('');try{await astanaRequest('/admin/publish','POST',{judgingRevision:revision});await refresh();setConfirmReveal(false);setMessage('The top three are now public.');}catch(e){setError((e as Error).message);}finally{setBusy(false);}}
 return <section><h2>Judges’ top three</h2><p className="astana-note mb-6">Select three different projects in order. Draft selections stay private until published.</p>{state.projects.length<3&&<Notice message="At least three submitted projects are needed to select the top three."/>}<div className="astana-form">{[0,1,2].map(i=><label key={i}>{['First place','Second place','Third place'][i]}<select value={ids[i]} onChange={e=>{setIds(prev=>prev.map((v,j)=>j===i?e.target.value:v));setDirty(true);setMessage('');}}><option value="">Choose a project</option>{state.projects.map(p=><option key={p.id} value={p.id}>{p.title} — {p.teamName}</option>)}</select></label>)}</div><Notice error message={error}/><Notice message={message}/><div className="astana-actions"><button className="btn" disabled={busy||new Set(ids.filter(Boolean)).size!==3} onClick={save}>Save private draft</button><button className="btn btn-primary" disabled={busy||dirty||state.draftProjectIds.length!==3} onClick={()=>setConfirmReveal(true)}>{state.publishedProjectIds.length?'Publish updated winners':'Publish winners'}</button>{error&&<button className="btn" onClick={()=>{setDirty(false);setError('');refresh();}}>Load latest draft</button>}</div>{confirmReveal&&<div className="astana-panel" role="group" aria-label="Confirm winner reveal"><h3>Ready to reveal?</h3><p>The saved top three will be visible to everyone.</p><div className="astana-actions"><button className="btn btn-primary" disabled={busy||dirty} onClick={publish}>Confirm public reveal</button><button className="btn" disabled={busy} onClick={()=>setConfirmReveal(false)}>Keep private</button></div></div>}</section>;
}
