import {useState} from 'react';
import type {Project} from '@shared/astana';
import {astanaRequest,useRefreshAstana} from '@/hooks/useAstana';
import {Notice} from './AstanaLayout';
export default function ProjectCard({project,allowVote=false,ownTeam=false,rank}:{project:Project;allowVote?:boolean;ownTeam?:boolean;rank?:number}){
 const [busy,setBusy]=useState(false),[error,setError]=useState(''),[rating,setRating]=useState<number|null>(null);const refresh=useRefreshAstana();
 async function vote(value:number){setBusy(true);setError('');try{await astanaRequest('/visitor','POST');await astanaRequest(`/projects/${project.id}/rating`,'PUT',{rating:value});setRating(value);await refresh();}catch(e){setError((e as Error).message);}finally{setBusy(false);}}
 return <article className="astana-project"><img src={project.thumbnailUrl} alt={`${project.title} preview`} loading="lazy" referrerPolicy="no-referrer" onError={e=>{e.currentTarget.onerror=null;e.currentTarget.src='/website/assets/viber-logo.png';}}/><div className="astana-project-body">{rank&&<p className="astana-rank">{['','1st place','2nd place','3rd place'][rank]}</p>}<p className="astana-note mb-2">{project.teamName}</p><h2>{project.title}</h2><p>{project.description}</p><div className="astana-actions"><a className="btn btn-primary" href={project.appUrl} target="_blank" rel="noopener noreferrer">Try the app ↗</a>{project.socialUrl&&<a className="btn" href={project.socialUrl} target="_blank" rel="noopener noreferrer">See the post ↗</a>}</div><p className="astana-note mb-3">{project.ratingCount?`${project.averageRating.toFixed(1)} / 5 · ${project.ratingCount} audience ratings`:'No ratings yet. Be the first to try it.'}</p>{allowVote&&!ownTeam&&<><div className="astana-stars" aria-label={`Rate ${project.title}`}>{[1,2,3,4,5].map(n=><button key={n} disabled={busy} aria-label={`Rate ${project.title} ${n} stars`} aria-pressed={rating===n} onClick={()=>vote(n)}>{n}★</button>)}</div>{rating&&<p role="status" className="astana-note mt-3">You rated {rating}/5. Tap another score to update.</p>}</>}{allowVote&&ownTeam&&<p className="astana-note">This is your team’s project.</p>}<Notice error message={error}/></div></article>;
}
