import {useEffect,useState} from 'react';
import type {Project,ProjectInput} from '@shared/astana';
import {astanaRequest,useRefreshAstana} from '@/hooks/useAstana';
import {Notice} from './AstanaLayout';
const values=(p:Project|null):ProjectInput=>({title:p?.title??'',description:p?.description??'',appUrl:p?.appUrl??'',thumbnailUrl:p?.thumbnailUrl??'',socialUrl:p?.socialUrl??'',revision:p?.revision??0});
export default function ProjectForm({project,teamId}:{project:Project|null;teamId:string}){
 const [form,setForm]=useState(()=>values(project)),[dirty,setDirty]=useState(false),[busy,setBusy]=useState(false),[error,setError]=useState(''),[message,setMessage]=useState('');const refresh=useRefreshAstana();
 useEffect(()=>{if(!dirty)setForm(values(project));},[project,dirty]);
 function change(key:keyof ProjectInput,value:string){setForm(f=>({...f,[key]:value}));setDirty(true);setMessage('');}
 async function save(e:React.FormEvent){e.preventDefault();setBusy(true);setError('');try{const saved=await astanaRequest<Project>('/project','PUT',{...form,teamId});setForm(values(saved));await refresh();setDirty(false);setMessage('Your project is live on the Astana launchpad.');}catch(e){setError((e as Error).message);}finally{setBusy(false);}}
 return <form onSubmit={save} className="astana-form"><label>Project name<input required maxLength={120} value={form.title} onChange={e=>change('title',e.target.value)}/></label><label>App URL<input required type="url" placeholder="https://your-app.com" value={form.appUrl} onChange={e=>change('appUrl',e.target.value)}/></label><label>Thumbnail image URL<input required type="url" placeholder="https://i.postimg.cc/…/image.png" value={form.thumbnailUrl} onChange={e=>change('thumbnailUrl',e.target.value)}/><small className="astana-note">Use the direct image link from <a className="astana-link" href="https://postimages.org" target="_blank" rel="noopener noreferrer">Postimages</a> or your image host, rather than the sharing page.</small></label><label>What does it do? <span className="astana-note">Optional · 500 characters</span><textarea maxLength={500} value={form.description} onChange={e=>change('description',e.target.value)}/></label><label>Tweet or social post URL <span className="astana-note">Optional</span><input type="url" placeholder="https://x.com/you/status/…" value={form.socialUrl??''} onChange={e=>change('socialUrl',e.target.value)}/></label><Notice error message={error}/><Notice message={message}/><button className="btn btn-primary" disabled={busy}>{busy?'Saving…':project?'Save project':'Launch project'}</button>{error&&<button type="button" className="btn" onClick={()=>{setForm(values(project));setDirty(false);setError('');}}>Discard my edits and load saved version</button>}</form>;
}
