import { useEffect, useRef, useState } from 'react';
import { Link, useNavigate } from 'react-router-dom';
import AstanaLayout,{Notice} from '@/components/astana/AstanaLayout';
import { astanaRequest,useAstana,useRefreshAstana } from '@/hooks/useAstana';
import type {Me} from '@shared/astana';
export default function AstanaJoin(){
 const navigate=useNavigate();const refresh=useRefreshAstana();const me=useAstana<Me>('/me');
 const [name,setName]=useState(''),[email,setEmail]=useState(''),[follow,setFollow]=useState(false),[busy,setBusy]=useState(false),[error,setError]=useState('');
 const recovering=useRef(false);
 useEffect(()=>{const value=new URLSearchParams(window.location.hash.slice(1)).get('recover');if(!value||recovering.current)return;recovering.current=true;history.replaceState(null,'',window.location.pathname);setBusy(true);astanaRequest('/recover','POST',{token:value}).then(()=>{refresh();navigate('/astana/team');}).catch(e=>setError(e.message)).finally(()=>setBusy(false));},[navigate,refresh]);
 async function submit(e:React.FormEvent){e.preventDefault();setBusy(true);setError('');try{await astanaRequest('/join','POST',{name,email,followConfirmed:follow});await refresh();navigate('/astana/team');}catch(e){setError((e as Error).message);}finally{setBusy(false);}}
 return <AstanaLayout><h1>You’re up, builder.</h1><p className="astana-lead mb-8">Free entry. Just your name and email, and you’re in the draw.</p>{me.data?.guest?<div className="astana-panel"><h2>You’re checked in, {me.data.guest.name}.</h2><Link className="btn btn-primary" to="/astana/team">See my team</Link></div>:<form className="astana-form" onSubmit={submit}><label>Your name<input autoComplete="name" required maxLength={100} value={name} onChange={e=>setName(e.target.value)}/></label><label>Email address<input type="email" autoComplete="email" required maxLength={254} value={email} onChange={e=>setEmail(e.target.value)}/></label><p className="astana-note">Your name appears with your team. Your email stays private with the organizers. Keep using this browser to access your team.</p><a className="btn" href="https://x.com/viberventures" target="_blank" rel="noopener noreferrer">Follow Viber on Twitter / X ↗</a><label className="astana-check"><input type="checkbox" required checked={follow} onChange={e=>setFollow(e.target.checked)}/><span>I’ve followed @viberventures.<small className="astana-note block">Your confirmation helps us stay connected after the event.</small></span></label><Notice error message={error}/><button className="btn btn-primary" disabled={busy||me.isLoading}>{busy?'Checking you in…':'Check in'}</button><p className="astana-note">Already registered in another browser? Ask the organizer to restore your access.</p></form>}</AstanaLayout>;
}
